apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-deployment
  namespace: gaitor-app
  labels:
    app: controller
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controller
  template:
    metadata:
      labels:
        app: controller
    spec:
      containers:
      - name: controller
        image: controller:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3001
        env:
        - name: DB_CONNECTION_STRING
          valueFrom:
            configMapKeyRef:
              name: database-config
              key: database-connection-string
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: sa-password
        - name: NODE_ENV
          value: "production"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"