apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-frontend
  namespace: gaitor-app
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-frontend
  template:
    metadata:
      labels:
        app: node-frontend
    spec:
      containers:
      - name: node-frontend
        image: node-frontend:1.0     # Built inside Minikube
        ports:
        - containerPort: 3000
