apiVersion: v1
kind: Service
metadata:
  name: ui-frontend
  namespace: gaitor-app
  labels:
    app: ui
spec:
  type: NodePort
  selector:
    app: node-frontend
  ports:
    - port: 3000         # Service port
      targetPort: 3000   # Container port
      nodePort: 30080    # Optional fixed NodePort (default: auto)
