apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: microservices-app
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
  - port: 1433
    targetPort: 1433
    protocol: TCP
    name: sqlserver